config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'pages#home'

  resources :vehicles do
    resources :reservations, only: [ :new, :create ]
  end
  resources :reservations, only: [ :show, :edit, :update, :destroy ]
  resources :users, only: [ :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle

  validates :date_start, presence: true
  validates :date_end, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_many :vehicles, dependent: :destroy
  has_many :reservations, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_one_attached :photo
  belongs_to :user

  validates :name, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true

  has_many :reservations, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController


  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(resevation_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @reservation.vehicle = @vehicle
    @reservation.user = current_user
    if @reservation.date_start < @reservation.date_end
      if @reservation.save
        redirect_to reservation_path(@reservation), notice: "Your Booking is Ok"
      else
        render :new, alert: 'Error your booking is not valid!'
      end
    else
      flash.now[:alert] = 'Error the end date must be greater than the start date!'
      render :new
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @duration = (@reservation.date_end - @reservation.date_start).to_i
    @reservation_price = @duration * @reservation.vehicle.price.to_i
  end



  private

  def resevation_params
    params.require(:reservation).permit(:date_start, :date_end, :comment, :vehicle_id, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user.id)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :find_vehicle, only: [:show, :edit, :update]


  def index
   # @vehicles = Vehicle.all

    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @vehicles = Vehicle.where(sql_query, query: "%#{params[:query]}%")
    else
      @vehicles = Vehicle.all
    end
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @vehicles.geocoded.map do |vehicle|
      {
        lat: vehicle.latitude,
        lng: vehicle.longitude
      }
    end

  end


  def show
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @vehicle.update(vehicle_params)
    redirect_to vehicle_path(@vehicle)
  end

  private

  def find_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:name, :address, :description, :price, :photo, :user, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VintageVehicleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)));">
  <div class="container banner-container">
    <h1>Find your dream <strong>Classic Vintage Car</strong>!</h1>
    <p>Choose among the largest list of Vintage Cars to rent</p>
    <%= link_to "Rent now", vehicles_path, class: "btn btn-gradient" %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-sm-9 col-md-6 offset-sm-2 offset-md-4">
      <div class="bg-white rounded p-3 shadow">
        <h3>Reservation for <%= @vehicle.name %></h3>
        <%= simple_form_for [@vehicle, @reservation] do |f| %>
        <%# <input type="date" name="born_on" id="born_on" /> %>
          <%= f.input :date_start, as: :date, order: [:day, :month, :year], label: 'Start date of booking'%>
          <%= f.input :date_end, as: :date, order: [:day, :month, :year], label: 'End date of booking' %>
          <%= f.input :comment, placeholder: 'Enter a comment' %>
          <%= f.submit class: 'btn btn-gradient' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="card-show">
  <div class="row">
    <div class="col-6 offset-3">
    <div class=".cards">
      <h1>Booking for <%= @reservation.user.email %></h1>
      <p>You rent a <%= @reservation.vehicle.name %> from <%= @reservation.date_start.strftime("%A %d %B %Y") %> to <%= @reservation.date_end.strftime("%A %d %B %Y")  %></p>
      <p> Cost of the rental for <%= @duration %> day = <%= @reservation_price  %>€ </p>
      <% if @reservation.vehicle.photo.attached?  %>
      <%= cl_image_tag @reservation.vehicle.photo.key, height: 300, width: 400, crop: :fill %>
      <p><%= link_to "Back to the List", vehicles_path, class: "btn btn-gradient bottom" %></p>
      <% end %>


    </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><%= alert %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <li class="nav-item">
          <%= link_to "Rent a car", vehicles_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Offer your car", new_vehicle_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user %>
                <%= link_to "My reservations", user_path(current_user), class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>




      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>User informations</h1>
<address>
E-mail: <%= @user.email %>
</address>

<h1>Your booking list</h1>
<div class="cards">
    <% @user.reservations.each do |reservation| %>
  <div class="card-trip">
    <% if reservation.vehicle.photo.attached?  %>
    <%= cl_image_tag reservation.vehicle.photo.key, height: 200, width: 300, crop: :fill %>
    <% end %>
    <p> You rent a <%= reservation.vehicle.name %> from <%= reservation.date_start.strftime("%A %d %B %Y") %> to <%= reservation.date_end.strftime("%A %d %B %Y")  %></p>
    <p><%= link_to "See details of the booking", reservation_path(reservation), class: "btn btn-gradient bottom" %></p>
  </div>
    <% end %>
</div>

app/views/vehicles/index.html.erb
<div class="container"></div>
<%= form_tag vehicles_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a vehicle"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>


      <h1>Find your next vehicle !</h1>

<div class="content">
  <div class="cards">
        <% @vehicles.each do |vehicle| %>
        <div class="card-trip">
          <% if vehicle.photo.attached?  %>
          <%= cl_image_tag vehicle.photo.key, height: 200, width: 300, crop: :fill %>
          <% end %>
          <h2><%= vehicle.name %></h2>
          <div class="des">
          <p><%= vehicle.description  %></p>
          </div>
          <p><u><strong>Price : <%= vehicle.price  %>€ per day</strong></u></p>
          <%= link_to "Show details", vehicle_path(vehicle),  class: "btn btn-gradient bottom"  %>
        </div>
        <% end %>
  </div>
  <div id="map"
     style="width:400%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Rent your vehicle</h3>
        <%= simple_form_for (@vehicle) do |f| %>
          <%= f.input :name, placeholder: 'Ford Mustang Fastback 67' %>
          <%= f.input :description, placeholder: 'Fully restored' %>
          <%= f.input :price, placeholder: '€ per day' %>
          <%= f.input :address, placeholder: 'Your address' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-gradient' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="card-show">
      <h2><%= @vehicle.name %></h2>
      <p><%= @vehicle.description %> </p>
      <p><u><em>Where to find the vehicle ? </em></u></p>
      <p><%= @vehicle.address  %></p>
      <p><u><strong>Price : <%= @vehicle.price  %>€ per day</u></strong></p>
      <% if @vehicle.photo.attached?  %>
      <%= cl_image_tag @vehicle.photo.key, height: 600, width: 800, crop: :fill %>
      <p><%= link_to "Book this car", new_vehicle_reservation_path(@vehicle), class: "btn btn-gradient" %></p>
      <% end %>
</div>